---
- name: Gather data from vault
  hosts: localhost
  gather_facts: no
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
    project_dir: "{{ lookup('env', 'PWD') }}"

  tasks:
    - name: Configure mount partitions
      command: mount -t cifs //172.30.253.14/backup_cleanroom /mnt -o cred=/etc/cifs_credentials,vers=2.0

    - name: Copy files from vault
      command: cp -r /mnt /ansible_k8_api_db/data
    
      