apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: johngaltdebugger/mywebapp:latest
        ports:
        - containerPort: 8001
        env:
          - name: DATABASE_HOST
            value: "{{ db_host }}"
